name: flutter_messenger
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  uuid: ^4.3.2
  intl:
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: FlutterChatIcons
      fonts:
        - asset: assets/fonts/icons/FlutterChatIcons.ttf
    - family: Gilroy-Thin
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
          weight: 100
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
